# -*- coding: utf-8 -*-
"""Hospital Appointment and Patient Management SYstem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kt59JCFCgqT2GthFl6mI6jXTMJ7rpIqW
"""

# ================= HOSPITAL APPOINTMENT SYSTEM =================
# Run this entire code in ONE Google Colab cell

print("📦 Installing Python packages...")
!pip install gradio -q

print("✅ Packages installed. Launching app...\n")

# ================= IMPORTS =================
import gradio as gr
import sqlite3
from datetime import datetime

# ================= DATABASE SETUP =================
def setup_database():
    conn = sqlite3.connect("hospital.db", check_same_thread=False)
    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        username TEXT PRIMARY KEY,
        password TEXT,
        role TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS appointments (
        appointment_id INTEGER PRIMARY KEY AUTOINCREMENT,
        patient_username TEXT,
        doctor_name TEXT,
        appointment_date TEXT,
        appointment_time TEXT,
        status TEXT
    )
    """)

    conn.commit()
    return conn, cursor

conn, cursor = setup_database()

# ================= GLOBAL USER SESSION =================
current_user = {"username": None, "role": None}

# ================= REGISTER =================
def register_user(username, password, role):
    if not username or not password:
        return "❌ All fields are required"

    try:
        cursor.execute(
            "INSERT INTO users VALUES (?, ?, ?)",
            (username, password, role)
        )
        conn.commit()
        return f"✅ Registered successfully as {role}"
    except sqlite3.IntegrityError:
        return "❌ Username already exists"

# ================= LOGIN =================
def login_user(username, password):
    cursor.execute(
        "SELECT role FROM users WHERE username=? AND password=?",
        (username, password)
    )
    result = cursor.fetchone()

    if result:
        current_user["username"] = username
        current_user["role"] = result[0]
        return f"✅ Logged in as {result[0]}"
    else:
        return "❌ Invalid login credentials"

# ================= BOOK APPOINTMENT =================
def book_appointment(doctor, date, time):
    if current_user["role"] != "Patient":
        return "❌ Only patients can book appointments"

    cursor.execute("""
        INSERT INTO appointments
        (patient_username, doctor_name, appointment_date, appointment_time, status)
        VALUES (?, ?, ?, ?, ?)
    """, (current_user["username"], doctor, date, time, "Pending"))

    conn.commit()
    return "✅ Appointment booked successfully (Pending approval)"

# ================= VIEW MY APPOINTMENTS (PATIENT) =================
def view_my_appointments():
    cursor.execute("""
        SELECT doctor_name, appointment_date, appointment_time, status
        FROM appointments WHERE patient_username=?
    """, (current_user["username"],))

    records = cursor.fetchall()
    if not records:
        return "📋 No appointments found"

    output = "📋 Your Appointments\n\n"
    for r in records:
        output += f"Doctor: {r[0]} | Date: {r[1]} | Time: {r[2]} | Status: {r[3]}\n"

    return output

# ================= VIEW ALL APPOINTMENTS (DOCTOR) =================
def view_all_appointments():
    if current_user["role"] != "Doctor":
        return "❌ Only doctors can view appointments"

    cursor.execute("SELECT * FROM appointments")
    records = cursor.fetchall()

    if not records:
        return "📋 No appointments available"

    output = "📋 All Appointments\n\n"
    for r in records:
        output += f"ID:{r[0]} | Patient:{r[1]} | Doctor:{r[2]} | {r[3]} {r[4]} | Status:{r[5]}\n"

    return output

# ================= UPDATE APPOINTMENT STATUS =================
def update_status(appointment_id, status):
    if current_user["role"] != "Doctor":
        return "❌ Only doctors can update status"

    cursor.execute("""
        UPDATE appointments SET status=?
        WHERE appointment_id=?
    """, (status, appointment_id))

    conn.commit()
    return "✅ Appointment status updated"

# ================= LOGOUT =================
def logout():
    current_user["username"] = None
    current_user["role"] = None
    return "✅ Logged out successfully"

# ================= USER INFO =================
def user_info():
    if current_user["username"]:
        return f"👤 {current_user['username']} ({current_user['role']})"
    return "👤 Not logged in"

# ================= GRADIO INTERFACE =================
with gr.Blocks(theme=gr.themes.Soft(), title="Hospital Appointment System") as app:

    gr.Markdown("# 🏥 Hospital Appointment & Patient Management System")
    user_status = gr.Markdown(user_info())

    with gr.Tabs():

        # ===== REGISTER =====
        with gr.Tab("📝 Register"):
            r_user = gr.Textbox(label="Username")
            r_pass = gr.Textbox(label="Password", type="password")
            r_role = gr.Radio(["Patient", "Doctor"], label="Role", value="Patient")
            r_btn = gr.Button("Register", variant="primary")
            r_out = gr.Textbox(label="Status", interactive=False)

            r_btn.click(register_user, [r_user, r_pass, r_role], r_out)

        # ===== LOGIN =====
        with gr.Tab("🔐 Login"):
            l_user = gr.Textbox(label="Username")
            l_pass = gr.Textbox(label="Password", type="password")
            l_btn = gr.Button("Login", variant="primary")
            l_out = gr.Textbox(label="Status", interactive=False)

            def login_update(u, p):
                msg = login_user(u, p)
                return msg, user_info()

            l_btn.click(login_update, [l_user, l_pass], [l_out, user_status])

        # ===== PATIENT DASHBOARD =====
        with gr.Tab("👨‍⚕️ Patient Dashboard"):
            doctor = gr.Textbox(label="Doctor Name")
            date = gr.Textbox(label="Appointment Date (YYYY-MM-DD)")
            time = gr.Textbox(label="Appointment Time (HH:MM)")
            b_btn = gr.Button("Book Appointment", variant="primary")
            b_out = gr.Textbox(label="Status", interactive=False)

            b_btn.click(book_appointment, [doctor, date, time], b_out)

            v_btn = gr.Button("View My Appointments", variant="secondary")
            v_out = gr.Textbox(lines=8, interactive=False)

            v_btn.click(view_my_appointments, outputs=v_out)

        # ===== DOCTOR DASHBOARD =====
        with gr.Tab("🩺 Doctor Dashboard"):
            a_btn = gr.Button("View All Appointments", variant="secondary")
            a_out = gr.Textbox(lines=10, interactive=False)

            a_btn.click(view_all_appointments, outputs=a_out)

            app_id = gr.Number(label="Appointment ID", precision=0)
            status = gr.Radio(["Approved", "Completed"], label="New Status")
            u_btn = gr.Button("Update Status", variant="primary")
            u_out = gr.Textbox(interactive=False)

            u_btn.click(update_status, [app_id, status], u_out)

        # ===== LOGOUT =====
        with gr.Tab("🚪 Logout"):
            lo_btn = gr.Button("Logout", variant="stop")
            lo_out = gr.Textbox(interactive=False)

            def logout_update():
                return logout(), user_info()

            lo_btn.click(logout_update, outputs=[lo_out, user_status])

    gr.Markdown("---")
    gr.Markdown("✅ Built for CSC 403 | Hospital Management Domain")

# ================= LAUNCH =================
app.launch(share=True, debug=True)

print("ended")

